module.exports = {
  name: '综合管廊管理系统',
  prefix: '管廊管理系统',
  footerText: 'Copyright © 2017 南京智行信息科技有限公司',
  logo: '/logo.png',
  BIM:'/BIM.png',
  markPoint:'/GIS/巡检人员.png',
  video:'/监控.png',
  fireDoor:'/fireEquipment/防火门.png',
  fireExtinguisher:'/fireEquipment/灭火器.png',
  escape:'/fireEquipment/逃生口.png',
  ladder:'/fireEquipment/梯子.png',
  ventilator:'/fireEquipment/通风口.png',
  oval:'/fireEquipment/椭圆.png',
  fireHydrant:'/fireEquipment/消防栓.png',
  smallFireDoor:'/fireEquipment/小防火门.png',
  hangingFireExtinguisher:'/fireEquipment/悬挂式灭火器.png',
  environmentBIM1:'/environment/BIM1.png',
  environmentBIM2:'/environment/BIM2.png',
  environmentCH4:'/environment/CH4.png',
  environmentH2S:'/environment/H2S.png',
  environmentO2:'/environment/O2.png',
  environmentWater:'/environment/积水深度.png',
  environmentHumidity:'/environment/湿度.png',
  environmentTemperature:'/environment/温度.png',
  fault:'/manage/故障单.png',
  undo:'/manage/未处理.png',
  doing:'/manage/进行中.png',
  done:'/manage/已完成.png',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  baseURL: 'http://192.168.0.103:8000/api',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: ['http://localhost:7000'],
  openPages: ['/login'],
  apiPrefix: '/api',
  api: {
    userLogin: '/user/login',
    userLogout: '/user/logout',
    userInfo: '/userInfo',
    users: '/users',
    user: '/user/:id',
    dashboard: '/dashboard',
    assets: '/equipment/assets',
    asset: '/equipment/asset/:id',
    monitorFire:'/monitor/subsystem/fire',
    fireEquipment:'/monitor/subsystem/fire/equipmentManage',
    monitorVentilation:'/monitor/subsystem/ventilation',
    ventilationEquipment:'/monitor/subsystem/ventilation/equipmentManage',
    monitorElectricity:'/monitor/subsystem/electricity',
    electricityEquipment:'/monitor/subsystem/electricity/equipmentManage',
    monitorIllumination:'/monitor/subsystem/illumination',
    illuminationEquipment:'/monitor/subsystem/illumination/equipmentManage',
    monitorDrain:'/monitor/subsystem/drain',
    drainEquipment:'/monitor/subsystem/drain/equipmentManage',
    monitorSecurity:'/monitor/subsystem/security',
    securityEquipment:'/monitor/subsystem/security/equipmentManage',
    monitorEnvironment:'/monitor/environment',
    environmentAlarmDetail:'/monitor/environment/:id',
    manageOverview:'/manage/overview',
    manageWorkForm:'/manage/workForm',
    manageForm:'/manage/workForm/:id',
    emergencys: '/emergency',
    emergency: '/emergency/:id',
  },
}
