module.exports = [
  {
    id: 1,
    icon: 'home',
    name: '综合信息概览',
    router: '/dashboard',
  },
  {
    id: 2,
    bpid: 1,
    name: '设备管理',
    icon: 'appstore-o',
  },
  {
    id: 21,
    bpid: 2,
    mpid: 2,
    name: '设备资产概览',
    icon: 'heart-o',
    router: '/equipment/overview',
  },
  {
    id: 22,
    bpid: 2,
    mpid: 2,
    name: '资产详情',
    icon: 'database',
    router: '/equipment/assets',
  },
  {
    id: 221,
    mpid: -1,
    bpid: 22,
    name: '设备详情',
    router: '/equipment/assets/:id',
  },
  // {
  //   id: 23,
  //   bpid: 2,
  //   mpid: 2,
  //   name: '库存管理',
  //   icon: 'bars',
  // },
  // {
  //   id: 231,
  //   bpid: 23,
  //   mpid: 23,
  //   name: '出入库管理',
  //   router: '/equipment/stock/access',
  // },
  // {
  //   id: 232,
  //   bpid: 23,
  //   mpid: 23,
  //   name: '采购管理',
  //   router: '/equipment/stock/purchase',
  // },
  // {
  //   id: 233,
  //   bpid: 23,
  //   mpid: 23,
  //   name: '报废管理',
  //   router: '/equipment/stock/scrap',
  // },
  {
    id: 3,
    bpid: 1,
    name: '智慧监测',
    icon: 'line-chart',
  },
  {
    id: 31,
    bpid: 3,
    mpid: 3,
    name: '附属设施监测',
  },
  {
    id: 311,
    bpid: 31,
    mpid: 31,
    name: '消防系统',
    router: '/monitor/subsystem/fire',
  },
  {
    id: 3111,
    bpid: 311,
    mpid: -1,
    name: '设备管理信息',
    router: '/monitor/subsystem/fire/equipmentManage',
  },
  {
    id: 312,
    bpid: 31,
    mpid: 31,
    name: '通风系统',
    router: '/monitor/subsystem/ventilation',
  },
  {
    id: 3121,
    bpid: 312,
    mpid: -1,
    name: '设备管理信息',
    router: '/monitor/subsystem/ventilation/equipmentManage',
  },
  {
    id: 313,
    bpid: 31,
    mpid: 31,
    name: '供电系统',
    router: '/monitor/subsystem/electricity',
  },
  {
    id: 3131,
    bpid: 313,
    mpid: -1,
    name: '设备管理信息',
    router: '/monitor/subsystem/electricity/equipmentManage',
  },
  {
    id: 314,
    bpid: 31,
    mpid: 31,
    name: '照明系统',
    router: '/monitor/subsystem/illumination',
  },
  {
    id: 3141,
    bpid: 314,
    mpid: -1,
    name: '设备管理信息',
    router: '/monitor/subsystem/illumination/equipmentManage',
  },
  {
    id: 315,
    bpid: 31,
    mpid: 31,
    name: '排水系统',
    router: '/monitor/subsystem/drain',
  },
  {
    id: 3151,
    bpid: 315,
    mpid: -1,
    name: '设备管理信息',
    router: '/monitor/subsystem/drain/equipmentManage',
  },
  {
    id: 316,
    bpid: 31,
    mpid: 31,
    name: '安防系统',
    router: '/monitor/subsystem/security',
  },
  {
    id: 3161,
    bpid: 316,
    mpid: -1,
    name: '设备管理信息',
    router: '/monitor/subsystem/security/equipmentManage',
  },
  {
    id: 32,
    bpid: 3,
    mpid: 3,
    name: '环境监测',
    router: '/monitor/environment',
  },
  {
    id: 321,
    mpid: -1,
    bpid: 32,
    name: '报警详情',
    router: '/monitor/environment/:id',
  },
  {
    id: 4,
    bpid: 1,
    name: 'BIM专题管理',
    icon: 'eye-o',
    router: '/BIM',
  },
  {
    id: 5,
    bpid: 1,
    name: '巡检管理',
    icon: 'solution',
  },
  {
    id: 51,
    bpid: 5,
    mpid: 5,
    name: '日常巡检',
    router: '/manage/overview',
  },
  {
    id: 52,
    bpid: 5,
    mpid: 5,
    name: '工单管理',
    router: '/manage/workForm',
  },
  {
    id: 53,
    bpid: 5,
    mpid: 5,
    name: '巡检人员定位',
    router: '/manage/GIS',
  },
  {
    id: 521,
    mpid: -1,
    bpid: 52,
    name: '工单详情',
    router: '/manage/workForm/:id',
  },
  // {
  //   id: 53,
  //   bpid: 5,
  //   mpid: 5,
  //   name: '事故报告',
  //   router: '/manage/accidentReport',
  // },
  {
    id: 6,
    bpid: 1,
    name: '应急管理',
    icon: 'api',
    router: '/emergency',
  },
  {
    id: 61,
    mpid: -1,
    bpid: 6,
    name: '应急预案详情',
    router: '/emergency/:id',
  },
  {
    id: 7,
    bpid: 1,
    name: '运维知识库',
    icon: 'database',
    router: '/library',
  },
  {
    id: 8,
    bpid: 1,
    name: '运维报表',
    icon: 'file-text',
    router: '/reportForm',
  },
]
